/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../../src/app/app.component';
import * as i2 from '@angular/common';
const styles_AppComponent:any[] = ([] as any[]);
export const RenderType_AppComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,styles:styles_AppComponent,
    data:{}});
function View_AppComponent_1(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'h1',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i0.ɵted((null as any),['Hello Angular']))],(null as any),(null as any));
}
function View_AppComponent_2(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'div',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i0.ɵted((null as any),['','']))],(null as any),(_ck,_v) => {
    const currVal_0:any = _v.context.$implicit;
    _ck(_v,1,0,currVal_0);
  });
}
export function View_AppComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'button',([] as any[]),
      (null as any),[[(null as any),'click']],(_v,en,$event) => {
        var ad:boolean = true;
        var _co:i1.AppComponent = _v.component;
        if (('click' === en)) {
          const pd_0:any = ((<any>_co.toggleHeading()) !== false);
          ad = (pd_0 && ad);
        }
        return ad;
      },(null as any),(null as any))),(_l()(),i0.ɵted((null as any),['Toggle Heading'])),
      (_l()(),i0.ɵted((null as any),['\n'])),(_l()(),i0.ɵand(16777216,(null as any),
          (null as any),1,(null as any),View_AppComponent_1)),i0.ɵdid(16384,(null as any),
          0,i2.NgIf,[i0.ViewContainerRef,i0.TemplateRef],{ngIf:[0,'ngIf']},(null as any)),
      (_l()(),i0.ɵted((null as any),['\n\n'])),(_l()(),i0.ɵeld(0,(null as any),(null as any),
          1,'h3',([] as any[]),(null as any),(null as any),(null as any),(null as any),
          (null as any))),(_l()(),i0.ɵted((null as any),['List of Heroes'])),(_l()(),
          i0.ɵted((null as any),['\n'])),(_l()(),i0.ɵand(16777216,(null as any),(null as any),
          1,(null as any),View_AppComponent_2)),i0.ɵdid(802816,(null as any),0,i2.NgForOf,
          [i0.ViewContainerRef,i0.TemplateRef,i0.IterableDiffers],{ngForOf:[0,'ngForOf']},
          (null as any))],(_ck,_v) => {
    var _co:i1.AppComponent = _v.component;
    const currVal_0:any = _co.showHeading;
    _ck(_v,4,0,currVal_0);
    const currVal_1:any = _co.heroes;
    _ck(_v,10,0,currVal_1);
  },(null as any));
}
export function View_AppComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'my-app',([] as any[]),
      (null as any),(null as any),(null as any),View_AppComponent_0,RenderType_AppComponent)),
      i0.ɵdid(49152,(null as any),0,i1.AppComponent,([] as any[]),(null as any),(null as any))],
      (null as any),(null as any));
}
export const AppComponentNgFactory:i0.ComponentFactory<i1.AppComponent> = i0.ɵccf('my-app',
    i1.AppComponent,View_AppComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiSDovQW5ndWxhcjIvYW90LXNhbXBsZS9zcmMvYXBwL2FwcC5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vSDovQW5ndWxhcjIvYW90LXNhbXBsZS9zcmMvYXBwL2FwcC5jb21wb25lbnQudHMiLCJuZzovLy9IOi9Bbmd1bGFyMi9hb3Qtc2FtcGxlL3NyYy9hcHAvYXBwLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vSDovQW5ndWxhcjIvYW90LXNhbXBsZS9zcmMvYXBwL2FwcC5jb21wb25lbnQudHMuQXBwQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPGJ1dHRvbiAoY2xpY2spPVwidG9nZ2xlSGVhZGluZygpXCI+VG9nZ2xlIEhlYWRpbmc8L2J1dHRvbj5cclxuPGgxICpuZ0lmPVwic2hvd0hlYWRpbmdcIj5IZWxsbyBBbmd1bGFyPC9oMT5cclxuXHJcbjxoMz5MaXN0IG9mIEhlcm9lczwvaDM+XHJcbjxkaXYgKm5nRm9yPVwibGV0IGhlcm8gb2YgaGVyb2VzXCI+e3toZXJvfX08L2Rpdj4iLCI8bXktYXBwPjwvbXktYXBwPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7OztvQkNDQTtNQUFBLHdFQUF3QjthQUFBOzs7b0JBR3hCO01BQUEsd0VBQWlDO2FBQUE7SUFBQTtJQUFBOzs7O29CQUpqQztNQUFBO1FBQUE7UUFBQTtRQUFRO1VBQUE7VUFBQTtRQUFBO1FBQVI7TUFBQSxnQ0FBa0M7TUFBdUIsdUNBQ3pEO1VBQUEsMkRBQUE7VUFBQTtNQUEwQyx5Q0FFMUM7VUFBQTtVQUFBLGdCQUFJLG1EQUFtQjtpQkFBQSx3QkFDdkI7VUFBQSw2Q0FBQTtVQUFBO1VBQUE7O0lBSEk7SUFBSixXQUFJLFNBQUo7SUFHSztJQUFMLFlBQUssU0FBTDs7OztvQkNKQTtNQUFBO2FBQUE7Ozs7In0=
